export const countries = [
    { code: 'ae', name: 'United Arab Emirates', flagCode: 'AE', isAvailable: false },
    { code: 'at', name: 'Austria', flagCode: 'AT', isAvailable: false },
    { code: 'au', name: 'Australia', flagCode: 'AU', isAvailable: false },
    { code: 'bg', name: 'Bulgaria', flagCode: 'BG', isAvailable: false },
    { code: 'br', name: 'Brazil', flagCode: 'BR', isAvailable: false },
    { code: 'ca', name: 'Canada', flagCode: 'CA', isAvailable: false },
    { code: 'cn', name: 'China', flagCode: 'CN', isAvailable: false },
    { code: 'co', name: 'Colombia', flagCode: 'CO', isAvailable: false },
    { code: 'cz', name: 'Czech Republic', flagCode: 'CZ', isAvailable: false },
    { code: 'de', name: 'Germany', flagCode: 'DE', isAvailable: false },
    { code: 'eg', name: 'Egypt', flagCode: 'EG', isAvailable: false },
    { code: 'fr', name: 'France', flagCode: 'FR', isAvailable: false },
    { code: 'gb', name: 'United Kingdom', flagCode: 'GB', isAvailable: false },
    { code: 'gr', name: 'Greece', flagCode: 'GR', isAvailable: false },
    { code: 'hk', name: 'Hong Kong', flagCode: 'HK', isAvailable: false },
    { code: 'hu', name: 'Hungary', flagCode: 'HU', isAvailable: false },
    { code: 'id', name: 'Indonesia', flagCode: 'ID', isAvailable: false },
    { code: 'ie', name: 'Ireland', flagCode: 'IE', isAvailable: false },
    { code: 'il', name: 'Israel', flagCode: 'IL', isAvailable: false },
    { code: 'in', name: 'India', flagCode: 'IN', isAvailable: false },
    { code: 'it', name: 'Italy', flagCode: 'IT', isAvailable: false },
    { code: 'jp', name: 'Japan', flagCode: 'JP', isAvailable: false },
    { code: 'kr', name: 'South Korea', flagCode: 'KR', isAvailable: false },
    { code: 'lt', name: 'Lithuania', flagCode: 'LT', isAvailable: false },
    { code: 'lv', name: 'Latvia', flagCode: 'LV', isAvailable: false }, // Corrected from 'fr' to 'lv' for Latvia
    { code: 'ma', name: 'Morocco', flagCode: 'MA', isAvailable: false },
    { code: 'mx', name: 'Mexico', flagCode: 'MX', isAvailable: false },
    { code: 'ng', name: 'Nigeria', flagCode: 'NG', isAvailable: false },
    { code: 'nl', name: 'Netherlands', flagCode: 'NL', isAvailable: false },
    { code: 'no', name: 'Norway', flagCode: 'NO', isAvailable: false },
    { code: 'nz', name: 'New Zealand', flagCode: 'NZ', isAvailable: false },
    { code: 'ph', name: 'Philippines', flagCode: 'PH', isAvailable: false },
    { code: 'pl', name: 'Poland', flagCode: 'PL', isAvailable: false },
    { code: 'pt', name: 'Portugal', flagCode: 'PT', isAvailable: false },
    { code: 'ro', name: 'Romania', flagCode: 'RO', isAvailable: false },
    { code: 'ru', name: 'Russia', flagCode: 'RU', isAvailable: false },
    { code: 'sa', name: 'Saudi Arabia', flagCode: 'SA', isAvailable: false },
    { code: 'sg', name: 'Singapore', flagCode: 'SG', isAvailable: false },
    { code: 'si', name: 'Slovenia', flagCode: 'SI', isAvailable: false },
    { code: 'sk', name: 'Slovakia', flagCode: 'SK', isAvailable: false },
    { code: 'th', name: 'Thailand', flagCode: 'TH', isAvailable: false },
    { code: 'tr', name: 'Turkey', flagCode: 'TR', isAvailable: false },
    { code: 'tw', name: 'Taiwan', flagCode: 'TW', isAvailable: false },
    { code: 'ua', name: 'Ukraine', flagCode: 'UA', isAvailable: false },
    { code: 'us', name: 'United States', flagCode: 'US', isAvailable: true },
    { code: 've', name: 'Venezuela', flagCode: 'VE', isAvailable: false },
    { code: 'za', name: 'South Africa', flagCode: 'ZA', isAvailable: false },
];
