export const topics = [
    "Technology",
    "Health",
    "Science",
    "Sports",
    "Finance",
    "Entertainment",
    "Politics",
    "Travel",
    "Education",
    "Lifestyle",
    "Food",
    "Art",
    "History",
    "Business",
    "Environment",
    "Automotive",
    "Fashion",
    "Home Improvement",
    "Gaming",
    "Cryptocurrency",
    "Psychology",
    "Parenting",
    "Self-Improvement",
    "Photography",
    "Relationships",
    "Hobbies",
    "News",
    "Current Events",
    "Local Events",
    "Social Issues",
    "Music",
    "Movies",
    "Mental Health",
    "Fitness",
    "Pets",
    "Gardening",
    "DIY Projects",
    "Real Estate",
    "Philosophy",
    "Technology Trends",
    "Artificial Intelligence",
    "Virtual Reality",
    "Sustainability",
    "Cultural Studies",
    "Global Affairs",
    "Personal Finance",
    "Marketing",
    "Startups",
    "E-commerce",
    "Event Planning",
    "Volunteering",
    "Fashion Trends",
    "Nutrition",
    "Crafting",
    "Spirituality",
    "Productivity",
    "Public Speaking",
    "Social Media",
    "Influencer Marketing",
    "Cryptography",
    "Data Science",
    "Software Development",
    "Web Development",
    "Mobile Apps",
    "Travel Tips",
    "Public Health",
    "Child Development",
    "Digital Marketing",
];
